// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TechnologyManager.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TechnologyManager.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Buffers {

namespace {

const ::google::protobuf::Descriptor* TechnologyManager_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TechnologyManager_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TechnologyManager_2eproto() {
  protobuf_AddDesc_TechnologyManager_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TechnologyManager.proto");
  GOOGLE_CHECK(file != NULL);
  TechnologyManager_descriptor_ = file->message_type(0);
  static const int TechnologyManager_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TechnologyManager, technologypoints_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TechnologyManager, possibleupgrades_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TechnologyManager, unavailableupgrades_),
  };
  TechnologyManager_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TechnologyManager_descriptor_,
      TechnologyManager::default_instance_,
      TechnologyManager_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TechnologyManager, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TechnologyManager, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TechnologyManager));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TechnologyManager_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TechnologyManager_descriptor_, &TechnologyManager::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TechnologyManager_2eproto() {
  delete TechnologyManager::default_instance_;
  delete TechnologyManager_reflection_;
}

void protobuf_AddDesc_TechnologyManager_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Buffers::protobuf_AddDesc_Unit_2eproto();
  ::Buffers::protobuf_AddDesc_UnitType_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027TechnologyManager.proto\022\007Buffers\032\nUnit"
    ".proto\032\016UnitType.proto\"\212\001\n\021TechnologyMan"
    "ager\022\030\n\020technologyPoints\030\001 \002(\005\022+\n\020possib"
    "leUpgrades\030\002 \003(\0132\021.Buffers.UnitType\022.\n\023u"
    "navailableUpgrades\030\003 \003(\0132\021.Buffers.UnitT"
    "ype", 203);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TechnologyManager.proto", &protobuf_RegisterTypes);
  TechnologyManager::default_instance_ = new TechnologyManager();
  TechnologyManager::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TechnologyManager_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TechnologyManager_2eproto {
  StaticDescriptorInitializer_TechnologyManager_2eproto() {
    protobuf_AddDesc_TechnologyManager_2eproto();
  }
} static_descriptor_initializer_TechnologyManager_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TechnologyManager::kTechnologyPointsFieldNumber;
const int TechnologyManager::kPossibleUpgradesFieldNumber;
const int TechnologyManager::kUnavailableUpgradesFieldNumber;
#endif  // !_MSC_VER

TechnologyManager::TechnologyManager()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TechnologyManager::InitAsDefaultInstance() {
}

TechnologyManager::TechnologyManager(const TechnologyManager& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TechnologyManager::SharedCtor() {
  _cached_size_ = 0;
  technologypoints_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TechnologyManager::~TechnologyManager() {
  SharedDtor();
}

void TechnologyManager::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TechnologyManager::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TechnologyManager::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TechnologyManager_descriptor_;
}

const TechnologyManager& TechnologyManager::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TechnologyManager_2eproto();
  return *default_instance_;
}

TechnologyManager* TechnologyManager::default_instance_ = NULL;

TechnologyManager* TechnologyManager::New() const {
  return new TechnologyManager;
}

void TechnologyManager::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    technologypoints_ = 0;
  }
  possibleupgrades_.Clear();
  unavailableupgrades_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TechnologyManager::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 technologyPoints = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &technologypoints_)));
          set_has_technologypoints();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_possibleUpgrades;
        break;
      }

      // repeated .Buffers.UnitType possibleUpgrades = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_possibleUpgrades:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_possibleupgrades()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_possibleUpgrades;
        if (input->ExpectTag(26)) goto parse_unavailableUpgrades;
        break;
      }

      // repeated .Buffers.UnitType unavailableUpgrades = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_unavailableUpgrades:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_unavailableupgrades()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_unavailableUpgrades;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TechnologyManager::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 technologyPoints = 1;
  if (has_technologypoints()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->technologypoints(), output);
  }

  // repeated .Buffers.UnitType possibleUpgrades = 2;
  for (int i = 0; i < this->possibleupgrades_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->possibleupgrades(i), output);
  }

  // repeated .Buffers.UnitType unavailableUpgrades = 3;
  for (int i = 0; i < this->unavailableupgrades_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->unavailableupgrades(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TechnologyManager::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 technologyPoints = 1;
  if (has_technologypoints()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->technologypoints(), target);
  }

  // repeated .Buffers.UnitType possibleUpgrades = 2;
  for (int i = 0; i < this->possibleupgrades_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->possibleupgrades(i), target);
  }

  // repeated .Buffers.UnitType unavailableUpgrades = 3;
  for (int i = 0; i < this->unavailableupgrades_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->unavailableupgrades(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TechnologyManager::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 technologyPoints = 1;
    if (has_technologypoints()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->technologypoints());
    }

  }
  // repeated .Buffers.UnitType possibleUpgrades = 2;
  total_size += 1 * this->possibleupgrades_size();
  for (int i = 0; i < this->possibleupgrades_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->possibleupgrades(i));
  }

  // repeated .Buffers.UnitType unavailableUpgrades = 3;
  total_size += 1 * this->unavailableupgrades_size();
  for (int i = 0; i < this->unavailableupgrades_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->unavailableupgrades(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TechnologyManager::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TechnologyManager* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TechnologyManager*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TechnologyManager::MergeFrom(const TechnologyManager& from) {
  GOOGLE_CHECK_NE(&from, this);
  possibleupgrades_.MergeFrom(from.possibleupgrades_);
  unavailableupgrades_.MergeFrom(from.unavailableupgrades_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_technologypoints()) {
      set_technologypoints(from.technologypoints());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TechnologyManager::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TechnologyManager::CopyFrom(const TechnologyManager& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TechnologyManager::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < possibleupgrades_size(); i++) {
    if (!this->possibleupgrades(i).IsInitialized()) return false;
  }
  for (int i = 0; i < unavailableupgrades_size(); i++) {
    if (!this->unavailableupgrades(i).IsInitialized()) return false;
  }
  return true;
}

void TechnologyManager::Swap(TechnologyManager* other) {
  if (other != this) {
    std::swap(technologypoints_, other->technologypoints_);
    possibleupgrades_.Swap(&other->possibleupgrades_);
    unavailableupgrades_.Swap(&other->unavailableupgrades_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TechnologyManager::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TechnologyManager_descriptor_;
  metadata.reflection = TechnologyManager_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Buffers

// @@protoc_insertion_point(global_scope)
